### PR TITLE
upgrade embedded consul to version 1.1.0

### PR DESCRIPTION
**Pull request by zyclonite**
fixed parameter "script" to "scriptArgs" for health checks

### CODE REVIEW

**Comment by vietj** [comment]
@zyclonite can you list the transitive dependency changes ?

**Comment by zyclonite** [comment]
no dependency was changed / it's still the embedded consul 1.0.0
there was only a default config in https://github.com/vert-x3/vertx-consul-client/blob/ada3c1a63ba60cc8293160efb028f211a2c22357/src/test/java/io/vertx/ext/consul/dc/ConsulAgentOptions.java#L26 pointing to consul binary version

in addition i reviewed the following projects
```
vertx-consul-service
vertx-config-consul
vertx-service-discovery-backend-consul
vertx-service-discovery-bridge-consul
```
no changes needed, no script-checks used

**Comment by ruslansennov** [comment]
> there was only a default config in

Could you confirm that tests pass if runs with
```
mvn -U -B -DCONSUL_AGENT_VERSION=0.7.5 test
```
We have a two steps on cloudbees.com to test this project: with default Consul version (was a 0.7.5) and with the newest version (1.0.x)

**Comment by zyclonite** [comment]
i doubt that the test was successful with the newest version (which is 1.1.0)... you would get a "Bad Request" from consul, trying to register a healthcheck with "script" as parameter...

i did not expect the 0.7.5 test to run...
do you think it makes sense to support < 1.0.0 versions of consul? hashicorp did break v1 api prior the 1.0.0 release "on purpose"

**Comment by ruslansennov** [comment]
> do you think it makes sense to support < 1.0.0 versions of consul?

I'm not sure this makes sense :) I was already thinking about increasing the minimum supported version of the Consul

**Comment by zyclonite** [comment]
if this goes out with 3.6.0, maybe a good idea :+1:

**Comment by zyclonite** [comment]
found out that with version 1.0.x the scriptArgs property was introduced (parallel to the script property)
with version 1.1.0 the script property was removed

**Comment by ruslansennov** [comment]
thank you

**Pull request merged**
